name: Question
description: Ask a question about RacerAPI.
title: "[Question]: "
labels:
  - question

body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
